### ISSUE TITLE
Discover with local data

### ISSUE THREAD

**Issue by LecrisUT** [LecrisUT/tmt-copr#2]
If there is test names defined, discover should act as if it populates
```yaml
/prefix:
  framework: copr
/prefix/pkg1
  package: pkg1
```
The local fmf files would then override this.

To research:
- https://github.com/teemtee/fmf/blob/29190c78e4065adf98cbb3ccf747b01973d761e2/fmf/base.py#L812-L815
